version: '3.8'

services:
  nginx:
    build: ./ngnix
    ports:
      - "80:80"
    depends_on:
      - auth
      - photo-upload
      - app
    networks:
      - app-network

  app:
    build: ..
    ports:
      - "8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://appuser:apppassword@db:5432/appdb
      - REDIS_URL=redis://redis:6379/0
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - YANDEX_GEOCODER_API_KEY=${YANDEX_GEOCODER_API_KEY}
      - GOOGLE_GEOCODER_API_KEY=${GOOGLE_GEOCODER_API_KEY}
      - TRANSFORMERS_OFFLINE=1
      - HF_HUB_OFFLINE=1
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
      - /home/lizardapn/.cache/huggingface/hub/:/root/.cache/huggingface/hub/ 
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  auth:
    build: ./AuthService
    ports:
      - "8001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://appuser:apppassword@db:5432/appdb
    networks:
      - app-network

  photo-upload:
    build: ./PhotoUploadService
    ports:
      - "8002"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://appuser:apppassword@db:5432/appdb
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - YANDEX_GEOCODER_API_KEY=${YANDEX_GEOCODER_API_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - IMAGE_PROCESSING_API_URL=http://app:8000
    networks:
      - app-network

  worker:
    build: ..
    command: celery -A src.tasks.worker worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://appuser:apppassword@db:5432/appdb
      - REDIS_URL=redis://redis:6379/0
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - YANDEX_GEOCODER_API_KEY=${YANDEX_GEOCODER_API_KEY}
      - TRANSFORMERS_OFFLINE=1
      - HF_HUB_OFFLINE=1
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
      - /home/lizardapn/.cache/huggingface/hub/:/root/.cache/huggingface/hub/ 
    networks:
      - app-network

  db:
    build: ./DB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - POSTGRES_DB=appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  pgdata:
  redis_data: