name: digital_hack_ml_job
desc: "Джоба для проведения экспериментов по созданию CV модели для определения местоположения по фотографии"

# Команда для запуска
cmd: python src/engine/main.py --csv-path csv_file_mob --images-dir images_dir_dzk/

# Используйте python: auto для автоматического определения версии Python
env:
  python: auto

# Входные данные (обновите алиасы)
inputs:
  - data/processed_data/merged_data.csv: csv_file_mob
  - data/raw_data/data/metadata/INC/united_image: images_dir_dzk
  - src/models: models
  - src/utils: utils

# Выходные данные
outputs:
  - optuna_study.pkl: optuna_study
  - ocr_model_params.json: ocr_model_params
  - test_results.json: test_results

cloud-instance-type: gt4.1