name: digital_hack_ml_job  # Уникальное имя задания
desc: "Джоба для проведения экспериментов по созданию CV модели для определения местоположения по фотографии" # Описание

# Команда для запуска. ${VARIABLE} - шаблоны, заменяемые на значения из `inputs`
cmd: python src/engine/main.py #--input ${INPUT_FILE}

# передать в DataSphere код и зависимости pip
env:
  python: auto

# Входные данные (файлы или каталоги)
#inputs:
#  - input_data.txt: INPUT_FILE  

# Выходные данные (файлы или каталоги, которые вернутся с облака)
#outputs:
#  - output_results.zip
#  - logs.txt

cloud-instance-type: gt4.1