# Параметры для обработки данных 
data:
  raw_path: "data/raw"
  processed_path: "data/processed"
  test_size: 0.2
  random_state: 42

# Параметры для фичей
features:
  numeric_features: 
    - "age"
    - "income"
  categorical_features:
    - "gender"
    - "education"

# Параметры модели
model:
  name: "random_forest"
  params:
    n_estimators: 100
    max_depth: 10
    random_state: 42

# Параметры обучения
training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  early_stopping_patience: 5

# Параметры логирования
logging:
  level: "INFO"
  file: "logs/training.log"